### ISSUE TITLE
Login error message for incorrect username.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#43]
There's an issue with the login error message for an incorrect username. When a user enters an incorrect username and a valid password, the system should display "Incorrect Username" and prevent login. Currently, it shows "Invalid details." Please update the error message to correctly indicate "Incorrect Username." This is a high-priority issue and needs urgent attention. Thank you!

**Comment by ridimatuladhar** [comment]
<img width="452" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/18eec827-400c-448a-8119-9bbf421ef8a4">
message for wrong email
