### ISSUE TITLE
Login error message for an empty username field.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#45]
There's an issue with the login error message for an empty username field. When a user leaves the username field empty and enters a valid password, the system should display "Please fill up the username" and prevent login. Currently, it shows "Invalid details." Please update the error message to correctly indicate "Please fill up the username."

**Comment by ridimatuladhar** [comment]
<img width="447" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/8cb917f1-cda0-4307-8d18-3782ae2ae09e">
fixed for empty username
