### ISSUE TITLE
Login error message for an empty password field.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#46]
There's an issue with the login error message for an empty password field. When a user leaves the password field empty and enters a valid username, the system should display "Please fill up the password" and prevent login. Currently, it shows "Invalid details." Please update the error message to correctly indicate "Please fill up the password".

**Comment by ridimatuladhar** [comment]
<img width="447" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/29b11f19-34db-4c7f-8d3b-cd1f2d8a368a">
fixed for empty password
