### ISSUE TITLE
Login error message for both username and password fields empty.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#47]
There's an issue with the login error message when both the username and password fields are empty. When a user leaves both fields empty, the system should display "Please fill up the username and password" and prevent login. Currently, it shows "Invalid details." Please update the error message to correctly indicate "Please fill up the username and password." This is a high-priority issue and needs urgent attention. Thank you.

**Comment by ridimatuladhar** [comment]
<img width="448" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/e8786f8f-1397-4b39-812e-d342b5e93553">
When both fields are empty.
