### ISSUE TITLE
Full name field validation on signup page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#48]
There's an issue with the full name field validation on the signup page. The full name field should reject special characters and numbers, but currently, it allows them. When a user enters a full name with special characters and numbers, the system incorrectly shows "Registration successful. Now you can login." Please update the validation to ensure the full name field does not accept special characters or numbers. This is a high-priority issue and needs urgent attention.

**Comment by MandipRaut** [comment]
Fixed. Now there appear a message if user input invalid name format. Also, the signup button would be disable until the username is valid to add.
Before: 
<img width="646" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119114781/b246758b-43f0-4696-849c-d71859af00db">

After:
<img width="645" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119114781/afc62c17-d0c2-4da2-b8aa-5642b8ab4728">
