### ISSUE TITLE
Issue with Phone Number Field Validation on Signup Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#49]
There's an issue with the phone number field validation on the signup page. The phone number field should accept only numeric input, but currently, it allows alphabetic characters. When a user enters a phone number with alphabetic characters, the system incorrectly shows "Registration successful." Please update the validation to ensure the phone number field accepts only numeric input and displays "Numerical Values only" if the input is invalid. This is a high-priority issue.

**Comment by MandipRaut** [comment]
Fixed!!!
Now user cannot enter any characters or symbols but only numbers in the phone number field.
 
Before:
<img width="644" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119114781/f203230c-d733-4eb2-953a-4143fe53d958">

After:
<img width="648" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119114781/29f273d3-3a83-4a8d-a28a-d6eb8d20cedf">
