### ISSUE TITLE
 Issue with License Number Field Validation and Verification on Signup Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#50]
The license number field on the signup page should only accept numeric input and be verified, but it currently allows non-numeric characters. This leads to incorrect registration success messages. Please update the validation to ensure numeric input and proper verification.

**Comment by MandipRaut** [comment]
Fixed!!!
Now only numbers could be entered into the license number input field.
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/30566a2e-e34d-49de-bf56-37596696fe26)
