### ISSUE TITLE
 Issue with Clear Reason Message Display for Invalid Credentials on Signup Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#51]
The signup page should display a clear reason message for invalid credentials when the "Sign up" button is clicked. However, it currently shows "Registration successful" even with invalid credentials. Please update the system to show the correct reason message.

**Comment by MandipRaut** [comment]
Fixed!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/3e84c9f4-781e-49a9-a645-ce99f7d74fac)
Now we can check if the email is available or not.
