### ISSUE TITLE
Vehicle Type Search Issue in Search Bar.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#53]
The search bar should allow searching for rental options based on vehicle type by selecting from the dropdown menu. However, the search button is not working, and rental options matching the selected vehicle type are not being displayed. Please fix the search button functionality to enable users to search for rental options based on vehicle type effectively.

**Comment by MandipRaut** [comment]
Fixed!!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/76eec13a-5fc2-4ee3-b89c-10b8b2d0d386)
Now we can get the searched car.
