### ISSUE TITLE
Missing Confirmation Prompt Issue for Cancel Booking Option.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#54]
When a customer selects the "Cancel Booking" option, a confirmation prompt should appear asking for cancellation confirmation. However, the confirmation prompt is not appearing when the customer selects cancel booking. Please address this issue to ensure customers see the confirmation prompt before cancelling a booking.

**Comment by kushal23456** [comment]
added confirmation on cancellation
<img width="458" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/165880127/89bacc0e-a246-4225-af78-b9cfce190461">
