### ISSUE TITLE
Missing Cancellation Policy Information in Confirmation Prompt.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#55]
The confirmation prompt displayed when cancelling a booking should include information about the cancellation policy, including any applicable fees. However, the confirmation prompt does not include the cancellation policy details. Please update the confirmation prompt to include the necessary information about the cancellation policy for better customer understanding and transparency.

**Comment by kushal23456** [comment]
added policy.
