### ISSUE TITLE
Inappropriate Empty Fields Message Issue on Admin Login Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#56]
When any of the login fields (email or password) are left empty on the admin login page, an appropriate message should be displayed indicating the need to fill in all login fields. However, the message currently displayed is "invalid details," which is not specific to the empty fields issue. Please update the message to clearly indicate the need to fill in all login fields when they are left empty.

**Comment by kushal23456** [comment]
![image](https://github.com/MandipRaut/CarRentalSystem/assets/165880127/92d2e072-0c21-4b47-9a2e-17f09e657bbc)
fixed
