### ISSUE TITLE
 Password Requirements Not Enforced on Admin Login.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#58]
The password for admin login should be at least 8 characters long and include letters, numbers, and special characters. However, the system allows passwords like "luna" that don't meet these requirements. We need to make sure the system enforces these password criteria and informs admins about the requirements.

**Comment by kushal23456** [comment]
Issue solved. 
![image](https://github.com/MandipRaut/CarRentalSystem/assets/165880127/3df56cbe-2fa0-4b01-98a3-8a84a2cedb6f)
