### ISSUE TITLE
Ineffective Management of Customer Queries in Admin Dashboard.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#59]
The admin should be able to effectively manage and view customer queries through the "Manage Contact Us Query" option in the admin dashboard. However, the admin currently cannot manage or view customer queries, including marking them as read or unread. Please address this issue to ensure the admin can efficiently handle customer queries in the admin dashboard. Thank you.

**Comment by MandipRaut** [comment]
Fixed!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/07681c7f-47ee-4865-bfed-63e488fe7b50)
Now the admin can read and mark read to user's queries.
