### ISSUE TITLE
Admin Unable to View Real-time Vehicle Locations on Map.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#60]
The admin should be able to view the real-time locations of booked vehicles on a map in the admin dashboard for efficient monitoring and management. However, the admin currently cannot access this feature, resulting in a failure to view real-time vehicle locations. Please address this issue to enable the admin to effectively monitor and manage vehicle locations on the map.

**Comment by ridimatuladhar** [comment]
<img width="1154" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/7536906e-92de-4963-b3a7-7738b0112b29">
can track location
