### ISSUE TITLE
Missing Inquiries View Issue on Admin Dashboard.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#61]
The admin should be able to view all inquiries/messages submitted through the contact form, including sender's name, email, and message content, in a proper table format on the dashboard. However, the admin currently cannot access the "Contact Us" page or section to view inquiries, resulting in a failure to view inquiries/messages. Please address this issue to enable the admin to efficiently manage inquiries on the dashboard.

**Comment by MandipRaut** [comment]
Fixed!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/b10d223b-bc2e-4842-a876-55331336c449)
Now the admin can read user's queries from the panel.
