### ISSUE TITLE
 Lack of Inquiry Status Tracking and Management on Admin Dashboard.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#62]
The admin dashboard should track the status of each inquiry, allowing admins to mark inquiries as read, pending, and resolved. However, the admin currently cannot track or manage inquiry statuses on the dashboard, resulting in a failure to effectively manage inquiry statuses. Please address this issue to enable the admin to track and manage inquiry statuses efficiently on the dashboard. Thank you.

**Comment by MandipRaut** [comment]
FIxed!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/1f61112d-c062-4c81-b029-235623288f4d)
Now admin can track user's query.
