### ISSUE TITLE
 Color Contrast Issue on About Us Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#64]
The color contrast on the About Us page is not matching, affecting readability and visual appeal. Please adjust the color scheme to improve contrast and ensure content is easily readable for users.

**Comment by AnuragSharma8** [comment]
<img width="399" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119913423/cf30d493-7443-41dc-8c49-b14957b10a50">
fixed: now the navigations are visible.
