### ISSUE TITLE
 Contact Us Page Formatting Issue.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#65]
The Contact Us page is not properly formatted, affecting its overall appearance and user experience. Please review and update the layout, styling, and alignment of elements on the Contact Us page to ensure a professional and cohesive look that is easy for users to navigate and interact with.

**Comment by AnuragSharma8** [comment]
the contact us page is now formatted
<img width="1324" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119678790/0a86ef65-e68a-42ac-9393-bf5ff228b2e4">
