### ISSUE TITLE
Hover Effect Issue on Send Message Button.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#66]
The hover effect on the Send Message button is not working as expected. Please review and fix the hover effect to ensure it provides a smooth and visually appealing transition when users hover over the button.

**Comment by AnuragSharma8** [comment]
Fixed. Now buttons have hover effect.
<img width="247" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119913423/0257e611-2980-46ad-9aa4-a26ff37d60a7">
