### ISSUE TITLE
Spelling Mistake in "Listen from our Customers" Section.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#67]
There is a spelling mistake in the "Listen from our Customers" section, where it appears as "Lisen from our Cuomers." Please correct the spelling mistake to ensure professional and error-free content on the page.

**Comment by AnuragSharma8** [comment]
The issue is fixed.
<img width="1145" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119913423/93819a30-27f2-443d-8945-402b16abc8dc">
