### ISSUE TITLE
Contact Info Placement and Text Update Issue on Contact Us Page.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#68]
The contact info section on the Contact Us page is currently centered but needs to be positioned above the "Get in touch using the form below" sentence. Additionally, the text "Get in touch using the form below" should be updated to "Get in touch with us! Please fill up the form below" for clarity and consistency. Please adjust the placement of the contact info and update the text as requested. Thank you.

**Comment by AnuragSharma8** [comment]
<img width="1143" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119913423/294a675e-beff-4769-b126-6448456da909">
now the CSS is fixed with a clear message.
