### ISSUE TITLE
 Inconsistent Password Confirmation Requirement.

### ISSUE THREAD

**Issue by LunaParajuliHerald** [MandipRaut/CarRentalSystem#78]
The password confirmation functionality on the signup page is not validating that the password and confirm password fields match. When a new password is entered and a different value is entered in the confirm password field, the system allows registration despite the mismatch. This inconsistency needs to be addressed to ensure that users enter matching passwords for successful registration.

**Comment by MandipRaut** [comment]
Fixed!!
![image](https://github.com/MandipRaut/CarRentalSystem/assets/119114781/434cfc1a-ab38-4bbf-baa0-c945b097de0d)
Now the password and confirm password must meet to signup.
