### ISSUE TITLE
Edit Button Not working

### ISSUE THREAD

**Issue by Biplabshah** [MandipRaut/CarRentalSystem#80]
On manage brand the edit button is not working. As a admin, i cant edit the brand.

**Comment by MandipRaut** [comment]
Fixed!!!
<img width="1091" alt="image" src="https://github.com/MandipRaut/CarRentalSystem/assets/119114781/2cca289f-0fff-481c-a2b4-fcc42f36bc1b">
Now you can edit a brand as shown in the image above.
